<Project>
  <PropertyGroup>
    <AppVersion>0.4.0</AppVersion>
    <Version>$(AppVersion)</Version>
    <AssemblyVersion>$(AppVersion).0</AssemblyVersion>
    <FileVersion>$(AppVersion).0</FileVersion>
    <InformationalVersion>$(AppVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <UseSharedCompilation>false</UseSharedCompilation>
  </PropertyGroup>
</Project>
