namespace DeepSeekHarnessDesktop.Services;

public enum HarnessStateEvent
{
    DshConfirmed,
    ReachableUnknown,
    ExternalRedirect,
    InvalidUri,
    InitializationAutoStart,
    InitializationStopped,
    Start,
    PreflightDshConfirmed,
    PreflightReachableUnknown,
    PreflightExternalRedirect,
    PreflightInvalidUri,
    PreflightUnreachable,
    HealthReady,
    Stop,
    Cancel,
    ProcessExited,
    Timeout,
    Error,
    Restart,
    HealthLost,
    ExternalAddressChanged,
    OldProcessExited,
    OldEndpointReleased,
    Retry,
    Dismiss,
}
